# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190329_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
