# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190401_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
