# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190404_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='post',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
