# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190401_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='project',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
