# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190401_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='grade',
            new_name='Content',
        ),
        migrations.AddField(
            model_name='votes',
            name='Design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votes',
            name='Usability',
            field=models.IntegerField(default=0),
        ),
    ]
