# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190401_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
