# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190403_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
