# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_votes_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='posted_on',
        ),
    ]
