# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_votes_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 17, 1, 28, 128127)),
        ),
    ]
