# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190403_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='Design',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='Usability',
        ),
        migrations.AddField(
            model_name='votes',
            name='content',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votes',
            name='design',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votes',
            name='usability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10),
            preserve_default=False,
        ),
    ]
