# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190403_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
